### ISSUE TITLE
NoneType object passed to os.path.join in portfolio.py

### ISSUE THREAD

**Issue by jtervala** [mhallsmoore/qsforex#17]
Hello. I am running Ubuntu 14.04 and have tried using this program. When I try to run trading.py I obtain the following error message:

Traceback (most recent call last):
  File "trading/trading.py", line 68, in <module>
    prices, events, equity=equity, backtest=False
  File "/home/justin/forexEnv/local/lib/python2.7/site-packages/qsforex/portfolio/portfolio.py", line 31, in __init__
    self.backtest_file = self.create_equity_file()
  File "/home/justin/forexEnv/local/lib/python2.7/site-packages/qsforex/portfolio/portfolio.py", line 74, in create_equity_file
    out_file = open(os.path.join(OUTPUT_RESULTS_DIR, filename), "w")
  File "/home/justin/forexEnv/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):

I would really appreciate your help, and thanks for making such a helpful blog.

Note: I doubt this would make much of a difference, but I was having a lot of difficulty installing scipy in a virtualenv so I used the --system-site-packages options when creating the virtualenv.

**Comment by mhallsmoore** [comment]
Hi jtervala,

Thanks for opening the issue. I'm going to try replicate the issue myself, on my own Python 2.7 build.

It may be due to the fact you haven't specified OUTPUT_RESULTS_DIR in your settings.py, as that would possibly explain the NoneType object passed to os.path.join exception.

Regards,

Mike.
