### ISSUE TITLE
getting the same error on multiple computer operation systems.

### ISSUE THREAD

**Issue by leolle** [mhallsmoore/qsforex#49]
Hi, Michael, I am getting this error under the virtual environment when executing this command:
`python trading/trading.py`
can you help? thank you.

`Traceback (most recent call last):
  File "trading/trading.py", line 49, in <module>
    logging.config.fileConfig('../logging.conf')
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
`

**Comment by dieterjansen** [comment]
Hi leolle,

The fix is relatively simple.

In trading.py change line 49 from using a path relative to your current directory (“../logging.conf”) to use an absolute path instead (for example something like “/home/leolle/projects/qsforex/logging.conf” depending on where you installed).

The way you tried to start trading.py is the way its described in the documentation but the program itself assumed you will be in the trading directory when you start it, contrary to the docs.

A more systematic fix is the subject of Pull Request https://github.com/mhallsmoore/qsforex/pull/39 but this is still pending.

Hope that helps – several of us in a small group in Adelaide Australia have been able to get the auto trading running against a practice account.

Cheers, Dieter.

From: leolle 
Sent: Friday, July 15, 2016 11:51 PM
To: mhallsmoore/qsforex 
Subject: [mhallsmoore/qsforex] getting the same error on multiple computer operation systems. (#49)

Hi, Michael, I am getting this error under the virtual environment when executing this command:
python trading/trading.py
can you help? thank you.

Traceback (most recent call last):
File "trading/trading.py", line 49, in <module>
logging.config.fileConfig('../logging.conf')
File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
formatters = _create_formatters(cp)
File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
flist = cp.get("formatters", "keys")
File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'

**Comment by leolle** [comment]
Hi Jansen, thank you very much for your advice, it works perfectly.
I changed the logging.conf file path to an absolute directory, it's find now.

**Comment by dieterjansen** [comment]
You’re welcome leolle, glad I could assist.

We’re all looking forward to starting work with QSTrader down here – Michael and several others have been putting in heaps of work on that recently.

Cheers, Dieter.

**Comment by leolle** [comment]
Hi Dieter,
Can I ask a question about the heartbeat?
Does the thread stop as the heartbeat interval if there is no new ticks
coming in? Does the thread resume back to work if there's new ticks coming
in?
How can I make my trading system working on a 5 or 15 minutes time frame
interval instead of tick by tick?

Thank you.

Regards,
Wei
